### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [TienVNguyen/NewYorkTimesProject#1]
### Thank you for your homework TienVNguyen.
- You really pushed effort on doing homework. - It's definitely the most complicated submission till now. It has everything an app needs to be commercial: nice UI, fantastic animation, various features...
### This is a few notes after checking out the code:
- Nice leverages the data binding support module to bind data into layout templates.
- Good use `HeterogeneousRecyclerView` with `CustomAdapter`. Read this for more detail: [Heterogeneous RecyclerView](https://guides.codepath.com/android/Heterogenous-Layouts-inside-RecyclerView)
- Nice using `DialogFragment`. This is such a very good article about [Dialog Fragment](https://guides.codepath.com/android/Using-DialogFragment).  
- I thought you already knew about android code style and MVP. But let it's more gorgeous by reading [Project and code style guidelines](https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md) and [MVP](https://github.com/ribot/android-guidelines/blob/master/architecture_guidelines/android_architecture.md)
- Create string value resource in `strings.xml` for maintain purpose. Try not to do `hardcode`.

Here's a detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you might be able to improve your submission.

**Comment by TienVNguyen** [comment]
Hi @coderschoolreview,

Great feedback. Hope to receive more in the future.

Thanks & Best Regards,
Tien Nguye
